### ISSUE TITLE
Build pipeline for expanded data set

### ISSUE THREAD

**Issue by karlie15** [jhirschibar/option_bot#25]
Having decided to go with the expanded data set, a new pipeline needs to be built out. 

Estimated time to complete: 2 days

Logic for going with the expanded data set is included below:

- Want to import calculations (get to modeling faster)
- want more columns at the get-go to see what is actually needed
- having data going back farther could be beneficial
- can cut back later once we develop our own calculations using their data to cross-check

**Comment by karlie15** [comment]
Will be adding the snapshot paginator class so that it can be downloaded for all stocks, including greeks.
Will also be downloading all quotes for all tickers.

ORM schemas will be added for both of these to easy upload to the DB

**Comment by jhirschibar** [comment]
> Will be adding the snapshot paginator class so that it can be downloaded for all stocks, including greeks.
> Will also be downloading all quotes for all tickers.
> 
> ORM schemas will be added for both of these to easy upload to the DB

I was actually the author of this

**Comment by jhirschibar** [comment]
Broken into #29 and #28
